name: Deploy Application  # Nome do workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ vars.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh root@${{ vars.SERVER_HOST }} "
          export NVM_DIR=\"\$HOME/.nvm\" &&
          [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\" &&
          cd ${{ vars.ROOT_PATH }} &&
          git pull &&
          nvm use 18 &&
          npm install &&
          npm run build &&
          pm2 restart ${{ vars.PM2_APP_NAME }}
        "
